ikt/ikt/Models/Ikt.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ikt.Models
{
    public partial class Ikt
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public string Link { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; } = "";
    }
}

ikt/ikt/Controllers/IktsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ikt.DAL;
using ikt.Models;
using ikt.ViewModels;

namespace ikt.Controllers
{
    public class IktsController : Controller
    {
        private iktContext db = new iktContext();

        // GET: Ikts
        public ActionResult Index()
        {
            var Ikts = db.Ikts.Include(P => P.ID);
            return View(db.Ikts.ToList());
        }

        // GET: Ikts/Details/5
        public ActionResult Details(int? id)
        {
            IktDetailsViewModel viewModel = new IktDetailsViewModel();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ikt ikt = db.Ikts.Find(id);
            if (ikt == null)
            {
                return HttpNotFound();
            }
            viewModel.Ikt = ikt;
            viewModel.IktClass = db.IktClasses.Where(i => i.IktID == id).ToList();
            viewModel.IktStaff = db.IktStaffs.Where(i => i.IktID == id).ToList();
            return View(viewModel);
        }

        // GET: Ikts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ikts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string Name, string ClassID, string Description, string Comment, string Link, string CreatedBy)
        {
            Ikt Ikts = new Ikt
            {
                Name = Name,
                Description = Description,
                Comment = Comment,
                Link = Link,
                CreatedBy = CreatedBy,
                CreatedDate = DateTime.Now
            };

            if (ModelState.IsValid)
            {
                Ikts.UpdatedDate = Ikts.CreatedDate;
                Ikts.UpdatedBy = Ikts.CreatedBy;
                db.Ikts.Add(Ikts);

                db.IktStaffs.Add(new IktStaff()
                {
                    IktID = Ikts.ID,
                    StaffID = db.Staff.Where(s => s.Username == Ikts.CreatedBy).Single().ID,
                    CreatedDate = DateTime.Now,
                    CreatedBy = Ikts.CreatedBy,
                    UpdatedDate = DateTime.Now,
                    UpdatedBy = Ikts.UpdatedBy
                });

                string[] classes;
                if (string.IsNullOrEmpty(ClassID))
                {
                    classes = new string[0];
                }
                else
                {
                    classes = ClassID.Split(',');
                }

                for (int i = 0; i < classes.Length; i++)
                {
                    db.IktClasses.Add(new IktClass()
                    {
                        IktID = Ikts.ID,
                        ClassID = Convert.ToInt32(classes[i]),
                        CreatedDate = DateTime.Now,
                        CreatedBy = Ikts.CreatedBy,
                        UpdatedDate = DateTime.Now,
                        UpdatedBy = Ikts.UpdatedBy
                    });
                }

                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(Ikts);
        }

        // GET: Ikts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ikt ikt = db.Ikts.Find(id);
            if (ikt == null)
            {
                return HttpNotFound();
            }
            List<IktClass> ic = db.IktClasses.Where(c => c.IktID == id).ToList();

            string klassList = "";
            foreach (var klass in ic)
            {
                klassList += klass.ClassID + ",";
            }
            if (klassList.Length > 0)
            {
                klassList = klassList.Substring(0, klassList.Length - 1);
            }
            ViewBag.ClassList = klassList;
            return View(ikt);
        }

        // POST: Ikts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int ID, string Name, string Description, string ClassID, string OldClassList, string Comment, string Link, string CreatedBy, string CreatedDate, string UpdatedBy)
        {
            Ikt Ikts = new Ikt
            {
                ID = ID,
                Name = Name,
                Description = Description,
                Comment = Comment,
                Link = Link,
                CreatedBy = CreatedBy,
                CreatedDate = DateTime.Parse(CreatedDate),
                UpdatedBy = UpdatedBy,
                UpdatedDate = DateTime.Now
            };

            if (ModelState.IsValid)
            {
                string[] newClasses;
                string[] oldClasses;
                if (string.IsNullOrEmpty(ClassID))
                {
                    newClasses = new string[0];
                }
                else
                {
                    newClasses = ClassID.Split(',');
                }
                if (string.IsNullOrEmpty(OldClassList))
                {
                    oldClasses = new string[0];
                }
                else
                {
                    oldClasses = OldClassList.Split(',');
                }
                List<string> remove = Constants.GetClassesToRemove(oldClasses, newClasses);
                List<string> add = Constants.GetClassesToAdd(oldClasses, newClasses);

                foreach (var toAdd in add)
                {
                    db.IktClasses.Add(new IktClass
                    {
                        ClassID = Convert.ToInt32(toAdd),
                        IktID = Ikts.ID,
                        CreatedDate = DateTime.Now,
                        CreatedBy = CreatedBy,
                        UpdatedDate = DateTime.Now,
                        UpdatedBy = CreatedBy
                    });
                }

                foreach (var toRemove in remove)
                {
                    int removeID = Convert.ToInt32(toRemove);
                    db.IktClasses.Remove(db.IktClasses.Where(c => c.ClassID == removeID && c.IktID == Ikts.ID).Single());
                }

                db.Entry(Ikts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = ID });
            }
            return View(Ikts);
        }

        // GET: Ikts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ikt ikt = db.Ikts.Find(id);
            if (ikt == null)
            {
                return HttpNotFound();
            }
            db.IktClasses.RemoveRange(db.IktClasses.Where(c => c.IktID == id));
            db.IktStaffs.RemoveRange(db.IktStaffs.Where(s => s.IktID == id));
            db.Ikts.Remove(ikt);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        // POST: Ikts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ikt ikt = db.Ikts.Find(id);
            db.Ikts.Remove(ikt);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult AddStaff(int iktID, int staffID)
        {
            IktStaff iktStaff = new IktStaff
            {
                StaffID = staffID,
                IktID = iktID,
                CreatedBy = db.Staff.Single(s => s.ID == staffID).Username,
                CreatedDate = DateTime.Now,
                UpdatedBy = db.Staff.Single(s => s.ID == staffID).Username,
                UpdatedDate = DateTime.Now
            };

            db.IktStaffs.Add(iktStaff);
            db.SaveChanges();

            return RedirectToAction("Details", new { id = iktID });
        }

        public ActionResult RemoveStaff(int id, int iktID)
        {
            db.IktStaffs.Remove(db.IktStaffs.Where(i => i.ID == id).Single());
            db.SaveChanges();

            return RedirectToAction("Details", new { id = iktID });
        }
    }
}

ikt/ikt/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ikt.DAL;
using ikt.Models;

namespace ikt.Controllers
{
    public class StaffsController : Controller
    {
        private iktContext db = new iktContext();

        // GET: Staffs/Create
        public ActionResult Create(string Username)
        {
            ViewBag.Username = Username;
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "ID,Username,FirstName,LastName,CreatedDate")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                staff.UpdatedDate = staff.CreatedDate;
                staff.UpdatedBy = staff.CreatedBy;
                db.Staff.Add(staff);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Username = staff.Username;
            return View(staff);
        }
    }
}

ikt/ikt/Views/Ikts/Create.cshtml
@model ikt.Models.Ikt

@{
    ViewBag.Title = "Lägger till Verktyg";
    ViewBag.Staff = Login.GetStaffInfo(User.Identity.Name);
    if (ViewBag.Staff.Username == "invalid")
    {
        Response.Redirect(Url.Action("Create", "Staffs", new { Username = User.Identity.Name.Split('@')[0] }));
    }
}

<h2>@ViewBag.Title</h2>

<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            @Html.ValidationSummary(true, "...", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Klass</label>
                <input type="text" class="form-control classList" id="ClassID" name="ClassID" />
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label" })
                @Html.TextAreaFor(model => model.Comment, new { @class = "form-control", @rows = "5" })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = "9" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <input type="text" name="CreatedBy" id="CreatedBy" value="@ViewBag.Staff.Username" hidden required />

    <div class="form-group">
        <a href="@Url.Action("Index", "Home")" class="btn btn-default"><i class="fas fa-arrow-left"></i> Tillbaka</a>
        <button type="submit" class="btn btn-default"><i class="fas fa-plus"></i> Lägg till</button>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ikt/ikt/Views/Ikts/Details.cshtml
@using ikt.Models
@model ikt.ViewModels.IktDetailsViewModel

@{
    ViewBag.Title = "Verktyg";
}

<h2>@Html.DisplayFor(model => model.Ikt.Name)</h2>
<h4>@ViewBag.Title</h4>
<hr />
<div class=" col-md-12">
    <div class="col-md-3">
        <div class="form-group">
            <dl>
                <dt>
                    Lärare
                </dt>
                @foreach (var staff in Model.IktStaff)
    {
            <dd>
                @staff.Staff.FirstName @staff.Staff.LastName
            </dd>
}
            </dl>
        </div>
        <div class="form-group">
            <dl>
                <dt>
                    Klasser
                </dt>
                @foreach (var klass in Model.IktClass)
                {
                    <dd>
                        @klass.Class.Name
                    </dd>
                }
            </dl>
        </div>
        <div class="form-group">
            <dl>
                @if (!string.IsNullOrEmpty(Model.Ikt.Link))
                {
                    <dt>
                            Länk
                    </dt>
                    <dd>
                        <a href="@Model.Ikt.Link" target="_blank">@Html.DisplayFor(model => model.Ikt.Link)</a>
                    </dd>
                }
            </dl>
        </div>
    </div>
    <div class="col-md-9">
        <div class="form-group">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.Ikt.Description)
                </dt>
                <dd class="descriptionBreaker">
                    @Html.DisplayFor(model => model.Ikt.Description)
                </dd>
            </dl>
        </div>
        <div class="form-group">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.Ikt.Comment)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Ikt.Comment)
                </dd>
            </dl>
        </div>
    </div>
</div>

<div class="row">
    @{
        ikt.DAL.iktContext iktContext = new ikt.DAL.iktContext();
        string username = (string)HttpContext.Current.Session["Username"];
        Staff currentStaff = iktContext.Staff.Where(s => s.Username == username).Single();
        IktStaff iktStaff = iktContext.IktStaffs.Where(s => s.IktID == Model.Ikt.ID && s.StaffID == currentStaff.ID).SingleOrDefault();
    }
    
</div>
<div class="form-group btn-StickBottom">
    <a href="@Url.Action("Index", "Home")" class="btn btn-default"><i class="fas fa-arrow-left"></i> Tillbaka</a>
    <a href="@Url.Action("Edit", new { id = Model.Ikt.ID })" class="btn btn-default"><i class="fas fa-edit"></i> Redigera</a>
    @if (iktStaff == null)
    {
        @Html.Raw(" ")
        <a href="@Url.Action("AddStaff", new { staffID = currentStaff.ID, iktID = Model.Ikt.ID })" class="btn btn-success">
            <i class="fas fa-user-plus"></i> Lägg till mig som användare av verktyget
        </a>
    }
    else
    {
        @Html.Raw(" ")
        <a href="@Url.Action("RemoveStaff", new { id = iktStaff.ID, iktID = Model.Ikt.ID })" class="btn btn-danger">
            <i class="fas fa-user-times"></i> Ta bort mig som användare av verktyget
        </a>
    }
    @Html.Raw(" ")
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal"><i class="fas fa-trash-alt"></i> Ta bort verktyget</button>
</div>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-danger">Varning!</h4>
            </div>
            <div class="modal-body">
                <h4>Är du säker på att du vill ta bort verktyget @Model.Ikt.Name?</h4>
            </div>
            <div class="modal-footer">
                <a href="@Url.Action("Delete",new { id = Model.Ikt.ID })" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Ta bort</a>
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fas fa-times"></i> Stäng</button>
            </div>
        </div>

    </div>
</div>

ikt/ikt/Views/Ikts/Edit.cshtml
@model ikt.Models.Ikt
@{
    ViewBag.Title = "Redigera";
}

<h2>@ViewBag.Title</h2>
<h4>Verktyg</h4>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Klass</label>
                <input type="text" class="form-control classList" id="ClassID" name="ClassID" value="@ViewBag.ClassList" />
                <input type="text" id="OldClassList" name="OldClassList" value="@ViewBag.ClassList" hidden />
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label" })
                @Html.TextAreaFor(model => model.Comment, new { @class = "form-control", @rows = "4" })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = "12" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <input type="text" name="CreatedDate" id="CreatedDate" value="@Model.CreatedDate" hidden required />
        <input type="text" name="CreatedBy" id="CreatedBy" value="@Model.CreatedBy" hidden required />
        @{
            string username = (string)HttpContext.Current.Session["Username"];
        }
        <input type="text" name="UpdatedBy" id="UpdatedBy" value="@username" hidden required />
    </div>
    <div class="form-group">
        <a href="@Url.Action("Details","Ikts",new { id = Model.ID })" class="btn btn-default"><i class="fas fa-arrow-left"></i> Tillbaka</a>
        <button type="submit" class="btn btn-default"><i class="fas fa-save"></i> Spara</button>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}