ikt/ikt/Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ikt.Models
{
    public partial class Project
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int? SubjectID { get; set; }
        public virtual Subject Subject { get; set; }
        public int Grade { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string PDF { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; } = "";
    }
}

ikt/ikt/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ikt.DAL;
using ikt.Models;
using ikt.ViewModels;

namespace ikt.Controllers
{
    public class ProjectsController : Controller
    {
        private iktContext db = new iktContext();

        // GET: Projects
        public ActionResult Index()
        {
            var projects = db.Projects.Include(p => p.Subject);
            return View(projects.ToList());
        }

        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            ProjectDetailsViewModel viewModel = new ProjectDetailsViewModel();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            viewModel.Project = project;
            viewModel.ProjectClass = db.ProjectClasses.Where(p => p.ProjectID == id).ToList();
            viewModel.ProjectStaff = db.ProjectStaffs.Where(p => p.ProjectID == id).ToList();
            return View(viewModel);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            ViewBag.SubjectID = new SelectList(db.Subjects.OrderBy(s => s.Name), "ID", "Name");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string Name, string SubjectID, string ClassID, int Grade, string Description, string Date, string CreatedBy, HttpPostedFileBase file)
        {
            Project project = new Project();
            int subjectID = 0;
            try
            {
                subjectID = db.Subjects.Where(s => s.Name == SubjectID).Single().ID;
            }
            catch
            {
                ModelState.AddModelError("SubjectID", "Ämnet finns inte.");
            }
            if (ModelState.IsValid)
            {
                project = new Project
                {
                    Name = Name,
                    SubjectID = subjectID,
                    Grade = Grade,
                    Description = Description,
                    Date = Date,
                    CreatedDate = DateTime.Now,
                    CreatedBy = CreatedBy,
                    UpdatedDate = DateTime.Now,
                    UpdatedBy = CreatedBy
                };
            }
            if (file != null)
            {
                if (ValidateFile(file))
                {
                    try
                    {
                        if (ModelState.IsValid)
                        {
                            Random r = new Random();
                            string newName;
                            do
                            {
                                newName = Convert.ToString(r.Next());
                            } while (System.IO.File.Exists(Constants.FilePath + newName));
                            newName += ".pdf";
                            SaveToDisk(file, newName);
                            project.PDF = newName;
                        }
                    }
                    catch (Exception e)
                    {
                        ModelState.AddModelError("PDF", "Ett okänt fel inträffade. Vänligen försök igen. " + e.Message);
                    }
                }
                else
                {
                    ModelState.AddModelError("PDF", "Filen " + file.FileName + " orsakade ett fel. Kolla att det är en PDF-fil och att den är mindre än " + Constants.MaxFileSizeMB + "MB");
                }
            }


            if (ModelState.IsValid)
            {
                db.Projects.Add(project);

                string[] classes;
                if (string.IsNullOrEmpty(ClassID))
                {
                    classes = new string[0];
                }
                else
                {
                    classes = ClassID.Split(',');
                }

                for (int i = 0; i < classes.Length; i++)
                {
                    db.ProjectClasses.Add(new ProjectClass
                    {
                        ClassID = Convert.ToInt32(classes[i]),
                        ProjectID = project.ID,
                        CreatedDate = DateTime.Now,
                        CreatedBy = CreatedBy,
                        UpdatedDate = DateTime.Now,
                        UpdatedBy = CreatedBy
                    });
                }

                db.ProjectStaffs.Add(new ProjectStaff
                {
                    StaffID = db.Staff.Where(s => s.Username == CreatedBy).Single().ID,
                    ProjectID = project.ID,
                    CreatedDate = DateTime.Now,
                    CreatedBy = CreatedBy,
                    UpdatedDate = DateTime.Now,
                    UpdatedBy = CreatedBy
                });

                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            
            return View(project);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.SubjectID = new SelectList(db.Subjects, "ID", "Name", project.SubjectID);

            List<ProjectClass> pc = db.ProjectClasses.Where(c => c.ProjectID == id).ToList();

            string klassList = "";
            foreach (var klass in pc)
            {
                klassList += klass.ClassID + ",";
            }
            if (klassList.Length > 0)
            {
                klassList = klassList.Substring(0, klassList.Length - 1);
            }
            ViewBag.ClassList = klassList;

            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int ID, string Name, int Grade, string SubjectID, string ClassID, string OldClassList, string PDF, string Description, string Date, string CreatedBy, string CreatedDate, string UpdatedBy, HttpPostedFileBase file)
        {
            Project project = new Project
            {
                ID = ID,
                Name = Name,
                SubjectID = db.Subjects.Where(s => s.Name == SubjectID).Single().ID,
                Grade = Grade,
                Description = Description,
                Date = Date,
                CreatedBy = CreatedBy,
                CreatedDate = DateTime.Parse(CreatedDate),
                UpdatedBy = UpdatedBy,
                UpdatedDate = DateTime.Now
            };

            if (file != null)
            {
                if (ValidateFile(file))
                {
                    try
                    {
                        if (ModelState.IsValid)
                        {
                            string newName;
                            if (string.IsNullOrEmpty(PDF))
                            {
                                Random r = new Random();
                                do
                                {
                                    newName = Convert.ToString(r.Next());
                                } while (System.IO.File.Exists(Constants.FilePath + newName));
                                newName += ".pdf";
                            }
                            else
                            {
                                newName = PDF;
                            }
                            SaveToDisk(file, newName);
                            project.PDF = newName;
                        }
                    }
                    catch (Exception e)
                    {
                        ModelState.AddModelError("PDF", "Ett okänt fel inträffade. Vänligen försök igen. " + e.Message);
                    }
                }
                else
                {
                    ModelState.AddModelError("PDF", "Filen " + file.FileName + " orsakade ett fel. Kolla att det är en PDF-fil och att den är mindre än " + Constants.MaxFileSizeMB + "MB");
                }
            }
            else if (!string.IsNullOrEmpty(PDF))
            {
                project.PDF = PDF;
            }


            if (ModelState.IsValid)
            {
                string[] newClasses;
                string[] oldClasses;
                if (string.IsNullOrEmpty(ClassID))
                {
                    newClasses = new string[0];
                }
                else
                {
                    newClasses = ClassID.Split(',');
                }
                if (string.IsNullOrEmpty(OldClassList))
                {
                    oldClasses = new string[0];
                }
                else
                {
                    oldClasses = OldClassList.Split(',');
                }
                List<string> remove = Constants.GetClassesToRemove(oldClasses, newClasses);
                List<string> add = Constants.GetClassesToAdd(oldClasses, newClasses);
                if (add.Count > 0)
                {
                    foreach (var toAdd in add)
                    {

ikt/ikt/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ikt.DAL;
using ikt.Models;

namespace ikt.Controllers
{
    public class StaffsController : Controller
    {
        private iktContext db = new iktContext();

        // GET: Staffs/Create
        public ActionResult Create(string Username)
        {
            ViewBag.Username = Username;
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "ID,Username,FirstName,LastName,CreatedDate")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                staff.UpdatedDate = staff.CreatedDate;
                staff.UpdatedBy = staff.CreatedBy;
                db.Staff.Add(staff);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Username = staff.Username;
            return View(staff);
        }
    }
}

ikt/ikt/Views/Projects/Create.cshtml
@model ikt.Models.Project

@{
    ViewBag.Title = "Lägger till Projekt";
    ViewBag.Staff = Login.GetStaffInfo(User.Identity.Name);
    if (ViewBag.Staff.Username == "invalid")
    {
        Response.Redirect(Url.Action("Create", "Staffs", new { Username = User.Identity.Name.Split('@')[0] }));
    }
}

<h2>@ViewBag.Title</h2>

<hr />
@using (Html.BeginForm("Create", "Projects", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.SubjectID, htmlAttributes: new { @class = "control-label" })
                <input type="text" class="form-control subjectList" id="SubjectID" name="SubjectID" required />
                @Html.ValidationMessageFor(model => model.SubjectID, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Klass</label>
                <input type="text" class="form-control classList" id="ClassID" name="ClassID" />
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PDF, htmlAttributes: new { @class = "control-label" })
                <div class="input-group pdfInput">
                    <label class="input-group-btn">
                        <span class="btn btn-default">
                            Välj fil... <input type="file" name="file" id="file" accept=".pdf" style="display: none;">
                        </span>
                    </label>
                    <input type="text" class="form-control" readonly>
                </div>
                @Html.ValidationMessageFor(model => model.PDF, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = "12" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label" })
                <input type="text" class="form-control" placeholder="Välj datum" name="Date" id="Date" required readonly />
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <input type="text" name="CreatedBy" id="CreatedBy" value="@ViewBag.Staff.Username" hidden required />
    <div class="form-group">
        <a href="@Url.Action("Index", "Home")" class="btn btn-default"><i class="fas fa-arrow-left"></i> Tillbaka</a>
        <button type="submit" class="btn btn-default"><i class="fas fa-plus"></i> Lägg till</button>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ikt/ikt/Views/Projects/Details.cshtml
@using ikt.Models
@model ikt.ViewModels.ProjectDetailsViewModel

@{
    ViewBag.Title = "Projekt";
}


<h2>@Html.DisplayFor(model => model.Project.Name)</h2>
<h4>@ViewBag.Title</h4>
<hr />
<script src="/Scripts/pdf.js"></script>

<script>
    // If absolute URL from the remote server is provided, configure the CORS
    // header on that server.
    var url = "/Content/ProjectFiles/@Model.Project.PDF";

    // Disable workers to avoid yet another cross-origin issue (workers need
    // the URL of the script to be loaded, and dynamically loading a cross-origin
    // script does not work).
    //PDFJS.disableWorker = true;

    // The workerSrc property shall be specified.
    PDFJS.workerSrc = '/Scripts/pdf.worker.js';

    // Asynchronous download of PDF
    var loadingTask = PDFJS.getDocument(url);
    loadingTask.promise.then(function (pdf) {
        console.log('PDF loaded');

        // Fetch the first page
        var pageNumber = 1;
        pdf.getPage(pageNumber).then(function (page) {
            console.log('Page loaded');

            var scale = 1.5;
            var viewport = page.getViewport(scale);

            // Prepare canvas using PDF page dimensions
            var canvas = document.getElementById('the-canvas');
            var context = canvas.getContext('2d');
            canvas.height = viewport.height;
            canvas.width = viewport.width;

            // Render PDF page into canvas context
            var renderContext = {
                canvasContext: context,
                viewport: viewport
            };
            var renderTask = page.render(renderContext);
            renderTask.then(function () {
                console.log('Page rendered');
            });
        });
    }, function (reason) {
        // PDF loading error
        console.error(reason);
    });
</script>

<div class=" col-md-12">
    <div class="col-md-3">
        <div class="form-group">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.Project.Subject.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Project.Subject.Name)
                </dd>
            </dl>
        </div>
        <div class="form-group">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.Project.Grade)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Project.Grade)
                </dd>
            </dl>
        </div>
        <div class="form-group">
            <dl>
                <dt>
                    Lärare
                </dt>
                @foreach (var staff in Model.ProjectStaff)
                {
                    <dd>
                        @staff.Staff.FirstName @staff.Staff.LastName
                    </dd>
                }
            </dl>
        </div>
        <div class="form-group">
            <dl>
                <dt>
                    Klasser
                </dt>
                @foreach (var klass in Model.ProjectClass)
                {
                    <dd>
                        @klass.Class.Name
                    </dd>
                }
            </dl>
        </div>
        <div class="form-group">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.Project.Date)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Project.Date)
                </dd>
            </dl>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.Project.Description)
                </dt>
                <dd class="descriptionBreaker">
                    @Html.DisplayFor(model => model.Project.Description)
                </dd>
            </dl>
        </div>
        @if (!string.IsNullOrEmpty(Model.Project.PDF))
        {
            <div class="form-group">
                <dl>
                    <dt>
                        @Html.DisplayNameFor(model => model.Project.PDF)
                    </dt>
                    <dd>
                        <a href="@Url.Content(Constants.FilePath + Model.Project.PDF)" target="_blank">
                            Visa PDF (öppnas i ny flik)
                        </a>
                    </dd>
                </dl>
            </div>
        }
    </div>
    <div class="col-md-5">
        <div class="form-group">
            @if (!string.IsNullOrEmpty(Model.Project.PDF))
            {
                <canvas id="the-canvas" class="col-md-12"></canvas>
            }
        </div>
    </div>
</div>
@{
    ikt.DAL.iktContext iktContext = new ikt.DAL.iktContext();
    string username = (string)HttpContext.Current.Session["Username"];
    Staff currentStaff = iktContext.Staff.Where(s => s.Username == username).Single();
    ProjectStaff projectStaff = iktContext.ProjectStaffs.Where(s => s.ProjectID == Model.Project.ID && s.StaffID == currentStaff.ID).SingleOrDefault();
}

<div class="form-group btn-StickBottom">
    <a href="@Url.Action("Index", "Home")" class="btn btn-default buttonStyle"><i class="fas fa-arrow-left"></i> Tillbaka</a>
    <a href="@Url.Action("Edit", new { id = Model.Project.ID })" class="btn btn-default buttonStyle"><i class="fas fa-edit"></i> Redigera</a>
    @if (projectStaff == null)
    {
        @Html.Raw(" ")
        <a href="@Url.Action("AddStaff", new { staffID = currentStaff.ID, projectID = Model.Project.ID })" class="btn btn-success buttonStyle">
            <i class="fas fa-user-plus"></i> Lägg till mig i projekt
        </a>
    }
    else
    {
        @Html.Raw(" ")
        <a href="@Url.Action("RemoveStaff", new { id = projectStaff.ID, projectID = Model.Project.ID })" class="btn btn-danger buttonStyle">
            <i class="fas fa-user-times"></i> Ta bort mig från projektet
        </a>
    }
    @Html.Raw(" ")
    <button type="button" class="btn btn-danger buttonStyle" data-toggle="modal" data-target="#myModal"><i class="fas fa-trash-alt"></i> Ta bort projektet</button>
</div>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-danger">Varning!</h4>
            </div>
            <div class="modal-body">
                <h4>Är du säker på att du vill ta bort projektet @Model.Project.Name?</h4>
            </div>
            <div class="modal-footer">
                <a href="@Url.Action("Delete",new { id = Model.Project.ID })" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Ta bort</a>
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fas fa-times"></i> Stäng</button>
            </div>
        </div>

    </div>
</div>

ikt/ikt/Views/Projects/Edit.cshtml
@model ikt.Models.Project
@{
    ViewBag.Title = "Redigera";
}

<h2>@ViewBag.Title</h2>
<h4>Projekt</h4>
<hr />

@using (Html.BeginForm("Edit", "Projects", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.SubjectID, htmlAttributes: new { @class = "control-label" })
                <input type="text" class="form-control" id="SubjectID" name="SubjectID" value="@Model.Subject.Name" required />
                @Html.ValidationMessageFor(model => model.SubjectID, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Klass</label>
                <input type="text" class="form-control classList" id="ClassID" name="ClassID" value="@ViewBag.ClassList" />
                <input type="text" id="OldClassList" name="OldClassList" value="@ViewBag.ClassList" hidden />
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
            @if (!string.IsNullOrEmpty(Model.PDF))
    {
        <div class="form-group">
            <label for="PDF">Uppladdad PDF</label>
            <dd>
                <a href="@Url.Content(Constants.FilePath + Model.PDF)" target="_blank">
                    Visa PDF (öppnas i ny flik)
                </a>
            </dd>
            @Html.HiddenFor(model => model.PDF)
        </div>
}
            <div class="form-group">
                <label for="file">Ny PDF</label>
                <div class="input-group pdfInput">
                    <label class="input-group-btn">
                        <span class="btn btn-default">
                            Välj fil... <input type="file" name="file" id="file" accept=".pdf" style="display: none;">
                        </span>
                    </label>
                    <input type="text" class="form-control" readonly>
                </div>
                @Html.ValidationMessageFor(model => model.PDF, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = "9" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.CreatedBy)
        @Html.HiddenFor(model => model.CreatedDate)
        @{
            string username = (string)HttpContext.Current.Session["Username"];
        }
        <input type="text" name="UpdatedBy" id="UpdatedBy" value="@username" hidden required />
    </div>
    <div class="form-group">
        <a href="@Url.Action("Details","Projects",new { id = Model.ID })" class="btn btn-default"><i class="fas fa-arrow-left"></i> Tillbaka</a>
        <button type="submit" class="btn btn-default"><i class="fas fa-save"></i> Spara</button>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}